name: ruminate
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  get: 4.1.4
  path_provider: ^2.0.2
  sliding_up_panel: 2.0.0+1
  id3:
    git: https://github.com/4-alok/id3.git
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_native_splash: ^0.3.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flutter_native_splash: 
  color: '#000000'
  image: assets/icon.png

